import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  async function handleOnSubmit(e) {
    e.preventDefault();
    const formData = {};
    Array.from(e.currentTarget.elements).forEach(field => {
      if(!field.name) return;
      formData[field.name] = field.value;
    });
    // 1st approach
    // fetch('api/mail', {
    //   method: 'post',
    //   body: JSON.stringify(formData),
    // })

    // 2nd approach
    fetch('/.netlify/functions/email-notification', {
      method: 'post',
      body: JSON.stringify(formData),
    })
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Contact form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Contact form
        </h3>
  
        <div className={styles.grid}>
          <style jsx>{`
            form {
              font-size: 1.2em;
            }

            label {
              display: block;
              margin-bottom: .2em;
            }

            input,
            textarea {
              width: 100%;
              padding: .8em;
            }

            button {
              color: white;
              font-size: 1em;
              background-color: blue;
              padding: .8em 1em;
              border: none;
              border-radius: .2em;
            }
          `}
          </style>
          <form method="post" onSubmit={handleOnSubmit}>
            <p>
              <label htmlFor="name">Name</label>
              <input type="text" name="name"/>
            </p>
            <p>
              <label htmlFor="email">Email</label>
              <input type="text" name="email"/>
            </p>
            <p>
              <label htmlFor="message">Message</label>
              <input type="text" name="message"/>
            </p>
            <p>
              <button>Submit</button>
            </p>
          </form>
        </div>
      </main>
    </div>
  )
}
